# Generated by Django 4.1.7 on 2023-03-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0027_alter_product_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='detalle',
        ),
        migrations.AlterField(
            model_name='product',
            name='precio',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='producto_imagen',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='tipomercancia',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
