# Generated by Django 4.1.7 on 2023-03-06 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0029_tipomercancia_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='123', max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('precio', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('producto_imagen', models.ImageField(default='', upload_to='images/')),
            ],
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='active',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='departamento',
            old_name='created',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='tipomercancia',
            old_name='active',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='tipomercancia',
            old_name='created',
            new_name='creado',
        ),
        migrations.RenameField(
            model_name='tipomercancia',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameModel(
            old_name='Department',
            new_name='Departamento',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='producto',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.departamento'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.tipomercancia'),
        ),
        migrations.AddField(
            model_name='producto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
